
package com.allaboutapple.WaWi.WaWiApplication.service.prodws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ProdWSPortType", targetNamespace = "https://www.deutschepost.de/ProductInformation/1.1/prodws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProdWSPortType {


    /**
     * 
     * @param parameter
     * @return
     *     returns com.allaboutapple.WaWi.WaWiApplication.service.prodws.SeekProductResponse
     */
    @WebMethod
    @WebResult(name = "seekProductResponse", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
    public SeekProductResponse seekProduct(
            @WebParam(name = "seekProductRequest", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
                    SeekProductRequestType parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.allaboutapple.WaWi.WaWiApplication.service.prodws.SeekProductVersionsResponse
     */
    @WebMethod
    @WebResult(name = "seekProductVersionsResponse", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
    public SeekProductVersionsResponse seekProductVersions(
            @WebParam(name = "seekProductVersionsRequest", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
                    SeekProductVersionsRequestType parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.allaboutapple.WaWi.WaWiApplication.service.prodws.GetProductResponse
     */
    @WebMethod
    @WebResult(name = "getProductResponse", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
    public GetProductResponse getProduct(
            @WebParam(name = "getProductRequest", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
                    GetProductRequestType parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.allaboutapple.WaWi.WaWiApplication.service.prodws.GetProductVersionsResponse
     */
    @WebMethod
    @WebResult(name = "getProductVersionsResponse", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
    public GetProductVersionsResponse getProductVersions(
            @WebParam(name = "getProductVersionsRequest", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
                    GetProductVersionsRequestType parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.allaboutapple.WaWi.WaWiApplication.service.prodws.GetProductListResponse
     */
    @WebMethod
    @WebResult(name = "getProductListResponse", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
    public GetProductListResponse getProductList(
            @WebParam(name = "getProductListRequest", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
                    GetProductListRequestType parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.allaboutapple.WaWi.WaWiApplication.service.prodws.GetProductVersionsListResponse
     */
    @WebMethod
    @WebResult(name = "getProductVersionsListResponse", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
    public GetProductVersionsListResponse getProductVersionsList(
            @WebParam(name = "getProductVersionsListRequest", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
                    GetProductVersionsListRequestType parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.allaboutapple.WaWi.WaWiApplication.service.prodws.GetChangedProductVersionsListResponse
     */
    @WebMethod
    @WebResult(name = "getChangedProductVersionsListResponse", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
    public GetChangedProductVersionsListResponse getChangedProductVersionsList(
            @WebParam(name = "getChangedProductVersionsListRequest", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
                    GetChangedProductVersionsListRequestType parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.allaboutapple.WaWi.WaWiApplication.service.prodws.RegisterEMailAdressResponse
     */
    @WebMethod
    @WebResult(name = "registerEMailAdressResponse", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
    public RegisterEMailAdressResponse registerEMailAdress(
            @WebParam(name = "registerEMailAdressRequest", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
                    RegisterEMailAdressRequestType parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.allaboutapple.WaWi.WaWiApplication.service.prodws.RegisterNotificationResponse
     */
    @WebMethod
    @WebResult(name = "registerNotificationResponse", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
    public RegisterNotificationResponse registerNotification(
            @WebParam(name = "registerNotificationRequest", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
                    RegisterNotificationRequestType parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.allaboutapple.WaWi.WaWiApplication.service.prodws.GetCatalogResponse
     */
    @WebMethod
    @WebResult(name = "getCatalogResponse", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
    public GetCatalogResponse getCatalog(
            @WebParam(name = "getCatalogRequest", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
                    GetCatalogRequestType parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.allaboutapple.WaWi.WaWiApplication.service.prodws.GetCatalogListResponse
     */
    @WebMethod
    @WebResult(name = "getCatalogListResponse", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
    public GetCatalogListResponse getCatalogList(
            @WebParam(name = "getCatalogListRequest", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
                    GetCatalogListRequestType parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.allaboutapple.WaWi.WaWiApplication.service.prodws.GetProductChangeInformationResponse
     */
    @WebMethod
    @WebResult(name = "getProductChangeInformationResponse", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
    public GetProductChangeInformationResponse getProductChangeInformation(
            @WebParam(name = "getProductChangeInformationRequest", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
                    GetProductChangeInformationRequestType parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns com.allaboutapple.WaWi.WaWiApplication.service.prodws.GetCatalogChangeInformationResponse
     */
    @WebMethod
    @WebResult(name = "getCatalogChangeInformationResponse", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
    public GetCatalogChangeInformationResponse getCatalogChangeInformation(
            @WebParam(name = "getCatalogChangeInformationRequest", targetNamespace = "urn:www-deutschepost-de:Product/ProductInformation/1.1/common", partName = "parameter")
                    GetCatalogChangeInformationRequestType parameter);

}
