
package com.allaboutapple.WaWi.WaWiApplication.service.prodws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProdWSService", targetNamespace = "https://www.deutschepost.de/ProductInformation/1.1/prodws", wsdlLocation = "https://prodws.deutschepost.de:8443/ProdWSProvider_1_1/prodws?wsdl")
public class ProdWSService
    extends Service
{

    private final static URL PRODWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ProdWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ProdWSService.class.getResource(".");
            url = new URL(baseUrl, "https://prodws.deutschepost.de:8443/ProdWSProvider_1_1/prodws?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://prodws.deutschepost.de:8443/ProdWSProvider_1_1/prodws?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PRODWSSERVICE_WSDL_LOCATION = url;
    }

    public ProdWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProdWSService() {
        super(PRODWSSERVICE_WSDL_LOCATION, new QName("https://www.deutschepost.de/ProductInformation/1.1/prodws", "ProdWSService"));
    }

    /**
     * 
     * @return
     *     returns ProdWSPortType
     */
    @WebEndpoint(name = "ProdWSPort")
    public ProdWSPortType getProdWSPort() {
        return super.getPort(new QName("https://www.deutschepost.de/ProductInformation/1.1/prodws", "ProdWSPort"), ProdWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProdWSPortType
     */
    @WebEndpoint(name = "ProdWSPort")
    public ProdWSPortType getProdWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.deutschepost.de/ProductInformation/1.1/prodws", "ProdWSPort"), ProdWSPortType.class, features);
    }

}
